# Generated by Django 5.0.2 on 2024-03-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('cognom', models.CharField(max_length=200)),
                ('edat', models.IntegerField()),
                ('correu', models.CharField(max_length=200)),
                ('rol', models.CharField(max_length=200)),
                ('moduls', models.CharField(max_length=200)),
            ],
        ),
    ]
